#!/bin/sh

. "$XDG_CONFIG_HOME/shell/functions"

alias sudo="sudo " # Makes aliases work with sudo
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias ls="ls --color=auto"
alias l.="ls -dl .*"
alias lsa="ls -lah"
alias c.="cd $XDG_CONFIG_HOME"
alias grep="grep --color"
alias v="nvim"
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tree=$HOME'

alias open=open

# Docker aliases
alias dcu="docker compose up -d"
alias dcd="docker compose down"
alias dim="docker images"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dsp="docker system prune --all"
alias dc=dc_fn
alias dex=dex_fn
alias di=di_fn
alias dip=dip_fn
alias dl=dl_fn
alias dnames=dnames_fn
alias drme=drme_fn
alias drmid=drmid_fn
alias drun=drun_fn
alias dsr=dsr_fn

