#!/bin/sh

open() {
  xdg-open "$@" &
}

dnames_fn() {
	for ID in $(docker ps | awk '{print $1}' | grep -v 'CONTAINER')
	do
    docker inspect "$ID" | grep Name | head -1 | awk '{print $2}' | sed 's/,//g' | sed 's%/%%g' | sed 's/"//g'
	done
}

dip_fn() {
  echo "IP addresses of all named running containers"

  for DOC in $(dnames_fn)
    do
      IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' "$DOC")
      printf "%s\n" "$DOC: $IP"
    done
}

dex_fn() {
	docker exec -it "$1" "${2:-sh}"
}

di_fn() {
	docker inspect "$1"
}

dl_fn() {
	docker logs -f "$1"
}

drun_fn() {
	docker run -itd "$@"
}

dsr_fn() {
  docker stop "$1";docker rm "$1"
}

drme_fn() {
  docker rm "$(docker ps --all -q -f status=exited)"
}

drmid_fn() {
  imgs=$(docker images -q -f dangling=true)
  [ -n "$imgs" ] && docker rmi "$imgs" || echo "no dangling images."
}

# in order to do things like dex $(dlab label) sh
dlab() {
  docker ps --filter="label=$1" --format="{{.ID}}"
}

dc_fn() {
  docker compose "$*"
}
