[window]
padding = { x = 6, y = 6 }
opacity = 0.8
blur = true

[font]
size = 7

[font.normal]
family = "JetBrainsMonoNerdFont" 
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
key = "C"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "K"
mods = "Shift|Alt"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "J"
mods = "Shift|Alt"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "U"
mods = "Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Alt"
action = "ScrollPageDown"

